name: Expresiones
run-name: Aprendiendo a usar expresiones

on:
  push:
    branches:
      - main
      - aprendiendo-**
  workflow_dispatch:
    inputs:
      edad:
        description: 'Edad'
        required: true
        type: integer
      nombre:
        description: 'Tu nombre'
        required: true
        default: 'Rosario'
        type: string

jobs:
  mayor:
    if: ${{ github.event_name == 'workflow_dispatch' && inputs.edad >= 18 }}
    runs-on: ubuntu-latest
    steps:
      - name: Mayor de edad
        run: echo "${{ inputs.nombre }} es mayor de edad"

  menor:
    if: ${{ github.event_name == 'workflow_dispatch' && inputs.edad < 18 }}
    runs-on: ubuntu-latest
    steps:
      - name: Menor de edad
        run: echo "${{ inputs.nombre }} es menor de edad"

  bonus:
    if: ${{ github.event_name == 'workflow_dispatch' && inputs.edad == 20 }}
    runs-on: ubuntu-latest
    steps:
      - name: Bonus edad 20
        run: echo "${{ inputs.nombre }} tiene 20"
