name: Expresiones
run-name: Aprendiendo a usar expresiones
on: 
  workflow_dispatch:
    inputs:
      edad:
        description: 'Edad'
        required: true
        type: integer
      nombre:
        description: 'Tu nombre'
        required: true
        default: 'Rosario'
        type: string
  jobs:
    mayor:
      if: ${{ inputs.edad >= 18}}
      runs-on: ubuntu-latest
      steps:
        - name: Correr script
          run: echo ${{ inputs.nombre}} es mayor de edad
    menor:
      if: ${{ inputs.edad < 18 }}
      runs-on: ubuntu-latest
      steps:
        - name: Correr script
          run: echo ${{ inputs.nombre }} es menor de edad
    bonus:
      if: ${{ inputs.edad == 20 }}
      runs-on: ubuntu-latest
      steps:
        - name: Correr script
          run: echo ${{ input.name }} tiene 20 
